### PR TITLE
Reorganise error handling

### LINKED ISSUE #199: Reconsider error handling in *Client
We have ugly code like this a few times in the tests

```ts
        try {
          await client.postTx(tx.value);
        } catch (error) {
          // postTx() throws on execution failures, which is a questionable design. Ignore for now.
          // console.log(error);
        }
```

This is because we throw exceptions for failed transaction. My feeling is we do not want to do that but instead return a union like `TxSuccess | TxFailure` and only throw for lower level errors.

### PR DESCRIPTION
**Pull request by willclarktech**
Closes #199

Currently errors are still thrown in some of the functions which wrap `postTx`.

### CODE REVIEW

File: packages/cosmwasm/src/cosmwasmclient.ts [hunk 1]
```diff
@@ -28,11 +28,26 @@ export interface Account {
...
   readonly rawLog: string;
   /** Transaction hash (might be used as transaction ID). Guaranteed to be non-empty upper-case hex */
   readonly transactionHash: string;
+  readonly data?: Uint8Array;
+}
+
+export type PostTxResult = PostTxSuccessResult | PostTxFailureResult;
+
+export function isPostTxFailureResult(postTxResult: PostTxResult): postTxResult is PostTxFailureResult {
+  return (postTxResult as PostTxFailureResult).code !== undefined;
```
Comment (webmaster128) [inline packages/cosmwasm/src/cosmwasmclient.ts:50]: We should check this for truthiness because the undefined server response just comes from JSON serializing a 0 error code: https://github.com/cosmos/cosmos-sdk/blob/v0.38.4/types/result.go#L77

Comment (willclarktech) [reply packages/cosmwasm/src/cosmwasmclient.ts:50]: Ah great, I assumed it was a lazy check but should have known better!
