### PR TITLE
Faucet fixes

### LINKED ISSUE #369: Faucet has hardcoded 200 tokens to distribution, fails if total below that.
Faucet is working now, but it doesn't work with such low values:
I put 100SHELL in the distribution account, as we give out 1 SHELL per user.

```
Aug 11 10:55:52 faucet docker[31029]: Sending 200 SHELL from coral1nkwhvtmdu5dm0yd4a8xvml3ktpdg9lhsqavygc to coral12x4sdtlt2zg9rexp405saahs3dellm>
Aug 11 10:55:52 faucet docker[31029]: Sending 200 SHELL from coral1nkwhvtmdu5dm0yd4a8xvml3ktpdg9lhsqavygc to coral1r8k9dwsryvuq6k05tgtwxzdxkwq7up>
Aug 11 10:55:52 faucet docker[31029]: Sending 200 SHELL from coral1nkwhvtmdu5dm0yd4a8xvml3ktpdg9lhsqavygc to coral1vr7lum34zwfz4w9meyyc4s9ce4k70h>
Aug 11 10:55:52 faucet docker[31029]: Sending 200 SHELL from coral1nkwhvtmdu5dm0yd4a8xvml3ktpdg9lhsqavygc to coral1fp2ntmn3f5vewyd0g3vlpqtmqy39ug>
Aug 11 10:55:52 faucet docker[31029]: Sending 200 SHELL from coral1nkwhvtmdu5dm0yd4a8xvml3ktpdg9lhsqavygc to coral1ucpr9rwudeaq0q2ux8a5gywx3ndrxu>
Aug 11 10:55:52 faucet docker[31029]: Done refilling accounts.
Aug 11 10:55:52 faucet docker[31029]: Holder:
Aug 11 10:55:52 faucet docker[31029]:   coral1nkwhvtmdu5dm0yd4a8xvml3ktpdg9lhsqavygc: [100 SHELL]
Aug 11 10:55:52 faucet docker[31029]: Distributors:
Aug 11 10:55:52 faucet docker[31029]:   coral12x4sdtlt2zg9rexp405saahs3dellmwa76s4ce: []
Aug 11 10:55:52 faucet docker[31029]:   coral1r8k9dwsryvuq6k05tgtwxzdxkwq7up3ngqpnhy: []
Aug 11 10:55:52 faucet docker[31029]:   coral1vr7lum34zwfz4w9meyyc4s9ce4k70hqcldz5ee: []
Aug 11 10:55:52 faucet docker[31029]:   coral1fp2ntmn3f5vewyd0g3vlpqtmqy39ug9rph7gxq: []
Aug 11 10:55:52 faucet docker[31029]:   coral1ucpr9rwudeaq0q2ux8a5gywx3ndrxusa7lvm62: []
```

I can work around this by sending 1000SHELL to the account, but maybe we can make this more dynamic (checking the token holders balance). Or maybe we can just use more tokens in the testnets.

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #369

Should be done but is not yet tested.

### CODE REVIEW

File: packages/faucet/src/faucet.ts [hunk 1]
```diff
@@ -50,10 +57,17 @@ export class Faucet {
...
+        amount: constants.fee,
+        gas: constants.gas,
+      },
+    };
+
     // we need one client per sender
     const clients: { [senderAddress: string]: SigningCosmosClient } = {};
     for (const [senderAddress, wallet] of wallets) {
-      clients[senderAddress] = new SigningCosmosClient(apiUrl, senderAddress, wallet);
+      clients[senderAddress] = new SigningCosmosClient(apiUrl, senderAddress, wallet, fees);
```
Comment (ethanfrey) [inline packages/faucet/src/faucet.ts:70]: Ahh... that was tricky, the cosm comes from the defaults in CosmosClient. Good find.

**Comment by ethanfrey** [comment]
Manually tested and it works perfect!

Tried with the same flags as before and got the proper error message about insufficient fees.
Added `FAUCET_FEES` and the tokens are loaded.

Nice one! Please tag and publish

**Comment by webmaster128** [comment]
Thank you, will merge locally and publich
